// <auto-generated />
using System;
using MRV.Leads.Platform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRV.Leads.Platform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240209125254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRV.Leads.Platform.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4ac97f0-9c7b-4b0f-bacc-694f4344f5c1"),
                            Email = "user1@example.com",
                            FullName = "Contact One",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("c1c6d0c4-ef52-48c7-bc2f-28958ffef95e"),
                            Email = "user2@example.com",
                            FullName = "Contact Two",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("c5457100-13dd-4462-8352-8c2a10e0e89b"),
                            Email = "user3@example.com",
                            FullName = "Contact Three",
                            PhoneNumber = "1020304050"
                        },
                        new
                        {
                            Id = new Guid("462547c5-3d29-4d46-89ab-0bf46f510782"),
                            Email = "user4@example.com",
                            FullName = "Contact Four",
                            PhoneNumber = "5040302010"
                        });
                });

            modelBuilder.Entity("MRV.Leads.Platform.Domain.Entities.Intent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Intents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8d5046a-87ea-4268-899d-6092151354f4"),
                            Active = true,
                            Category = 1,
                            ContactId = new Guid("e4ac97f0-9c7b-4b0f-bacc-694f4344f5c1"),
                            CreatedDate = new DateTime(2024, 2, 9, 12, 52, 53, 562, DateTimeKind.Utc).AddTicks(3053),
                            Description = "Initial intent",
                            Price = 99.99m,
                            Status = 0,
                            Suburb = "Yandera 2574"
                        },
                        new
                        {
                            Id = new Guid("f67e0a23-b99f-4c1b-89f0-4f65c83eff26"),
                            Active = true,
                            Category = 2,
                            ContactId = new Guid("c1c6d0c4-ef52-48c7-bc2f-28958ffef95e"),
                            CreatedDate = new DateTime(2024, 2, 9, 12, 52, 53, 562, DateTimeKind.Utc).AddTicks(3060),
                            Description = "Second intent",
                            Price = 99.99m,
                            Status = 0,
                            Suburb = "Woolooware 2230"
                        },
                        new
                        {
                            Id = new Guid("4fc22a04-06d8-4e89-a9b0-380de22b1e39"),
                            Active = true,
                            Category = 4,
                            ContactId = new Guid("c5457100-13dd-4462-8352-8c2a10e0e89b"),
                            CreatedDate = new DateTime(2024, 2, 9, 12, 52, 53, 562, DateTimeKind.Utc).AddTicks(3064),
                            Description = "Thirty intent",
                            Price = 699.99m,
                            Status = 1,
                            Suburb = "Caramar 6031"
                        },
                        new
                        {
                            Id = new Guid("70b81aad-be1b-492f-9c7e-5684af79ae01"),
                            Active = true,
                            Category = 3,
                            ContactId = new Guid("462547c5-3d29-4d46-89ab-0bf46f510782"),
                            CreatedDate = new DateTime(2024, 2, 9, 12, 52, 53, 562, DateTimeKind.Utc).AddTicks(3068),
                            Description = "Fourthy intent",
                            Price = 499.99m,
                            Status = 1,
                            Suburb = "Quinss Rocks 6030"
                        });
                });

            modelBuilder.Entity("MRV.Leads.Platform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42a11b3e-5d94-423f-bec0-c9c034fdb8f4"),
                            Active = false,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@example.com",
                            Login = "user1",
                            PasswordHash = "SomeHashedPassword"
                        },
                        new
                        {
                            Id = new Guid("2c85deda-d510-4c37-9c31-fc691bb7d9d6"),
                            Active = false,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@example.com",
                            Login = "user2",
                            PasswordHash = "SomeHashedPassword"
                        });
                });

            modelBuilder.Entity("MRV.Leads.Platform.Domain.Entities.Intent", b =>
                {
                    b.HasOne("MRV.Leads.Platform.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
